# Generated by Django 2.2 on 2020-05-21 02:25

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0004_auto_20200521_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='profile',
            field=models.ForeignKey(default=datetime.datetime(2020, 5, 21, 2, 25, 3, 323577, tzinfo=utc), null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile'),
            preserve_default=False,
        ),
    ]
